### PR TITLE
[automated] Update community lists

### PR DESCRIPTION
**Pull request by chris-y**
Update community lists generated automatically

### CODE REVIEW

**Comment by chris-y** [comment]
This adds "general artworks".
Need to add to deploy.sh before merging.

**Comment by M4rtineski** [comment]
Can't wait to see the new script in action.

**Comment by chris-y** [comment]
I've written some notes on how to add a new bot.
There are way more steps than I'd like but at least the lists don't need to be manually kept up to date now.
https://github.com/fnic-lemmy/bestofbot/wiki

**Comment by M4rtineski** [comment]
I will leave this part to you anyway because it's too technical to me to casually do it without spending time on figuring that out. :3

**Pull request merged**
